name: budget_app_pk
description: A comprehensive budget management app designed for Pakistani users
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # UI Components
  cupertino_icons: ^1.0.6
  material_color_utilities: ^0.5.0
  
  # Charts and Graphs
  fl_chart: ^0.65.0
  
  # Date and Time
  intl: ^0.18.1
  
  # Utilities
  uuid: ^4.2.1
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  
  # Icons
  phosphor_flutter: ^2.0.1
  
  # Animations
  lottie: ^2.7.0
  
  # Image handling
  image_picker: ^1.0.4
  
  # File handling
  file_picker: ^6.1.1
  
  # Notifications
  flutter_local_notifications: ^16.3.0
  
  # Currency formatting
  money2: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
    - family: NotoSansUrdu
      fonts:
        - asset: fonts/NotoSansUrdu-Regular.ttf
        - asset: fonts/NotoSansUrdu-Medium.ttf
          weight: 500
        - asset: fonts/NotoSansUrdu-Bold.ttf
          weight: 700
